#Application Settings
#Mon Apr 20 12:24:33 GMT+08:00 2026
app.cancelTime=Never
app.identifier=staff-app-01
database.deleteTime=3 months
message.enabled.message.cancelled=false
message.enabled.message.complete=false
message.enabled.message.confirm=false
message.enabled.message.new=false
message.label.message.cancelled=Cancelled Reservation
message.label.message.complete=Complete Reservation
message.label.message.confirm=Confirm Reservation
message.label.message.new=New Reservation
message.label.message.notify_customer=Notify Customer
message.pane.api.toggle=true
server.url=https\://java-reservationsystem.onrender.com
sms.controller=No Controller Detected
sms.module=No Module Detected
sms.phone=No SIM Card Detected
website.url=
websocket.url=wss\://java-reservationsystem.onrender.com/raw-ws
