# ReservationSystem Configuration

website.url=https://reservationsystem-ul0w.onrender.com
server.url=https://reservationsystem-ul0w.onrender.com
websocket.url=wss://reservationsystem-ul0w.onrender.com/ws

philsms.api.token=
philsms.sender.id=PhilSMS