# ReservationSystem Configuration

# ================= LOGGING =================
logging.level.root=INFO
logging.level.org.apache=WARN
logging.level.com.zaxxer=WARN

# ================= MESSAGING =================
website.url=${WEBSITE_URL:}
server.url=${SERVER_URL:}