# ================= LOGGING =================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.apache=WARN

# ================= LOGGING =================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN
logging.level.org.apache=WARN
logging.level.com.zaxxer=WARN
logging.level.org.hibernate.orm.deprecation=WARN
logging.level.org.hibernate.orm.jdbc.bind=OFF

# ================= PHILSMS (use env vars) =================
philsms.api.token=${PHILSMS_TOKEN}
philsms.sender.id=${PHILSMS_SENDER_ID}

# ================= WEBSITE =================
website.url=${WEBSITE_URL}
server.url=${SERVER_URL}
